# version: '3.8'  # Specify the version of Docker Compose

services:
  # PostgreSQL service
  postgres:
    image: postgres:13  # Use the official PostgreSQL image version 13
    environment:
      POSTGRES_USER: airflow  # Set the PostgreSQL user to 'airflow'
      POSTGRES_PASSWORD: letmeinplease  # Set the PostgreSQL password to 'airflow'
      POSTGRES_DB: airflow  # Set the PostgreSQL database name to 'airflow'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data  # Persist PostgreSQL data

  # pgAdmin webserver service
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dhakalpa@mail.uc.edu
      PGADMIN_DEFAULT_PASSWORD: letmeinplease
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - postgres

  # Airflow webserver service
  webserver:
    build: .
    image: custom_airflow:latest # Use the official Apache Airflow image version 2.4.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor  # Use LocalExecutor for Airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:letmeinplease@postgres/airflow  # Database connection string
      #AIRFLOW__CORE__FERNET_KEY: 'OExH4KfzQbFU9f2DltIorH3jDP6bHCjSIOXcjssHImM='  # Optional: Fernet key for encryption
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'  # Load example DAGs
      AIRFLOW__WEBSERVER__RBAC: 'true'  # Enable Role-Based Access Control (RBAC)
    volumes:
      - ./dags:/opt/airflow/dags  # Mount local 'dags' directory to Airflow 'dags' directory
      - ./logs:/opt/airflow/logs  # Mount local 'logs' directory to Airflow 'logs' directory
      - ./plugins:/opt/airflow/plugins  # Mount local 'plugins' directory to Airflow 'plugins' directory
      - ./data:/opt/airflow/data # Mount local 'data' directory to Airflow 'data' directory
    ports:
      - "8080:8080"  # Expose port 8080 for the webserver
    depends_on:
      - postgres  # Ensure the PostgreSQL service is started before the webserver
    command: webserver  # Command to run the Airflow webserver

  # Airflow scheduler service
  scheduler:
    build: .
    image: custom_airflow:latest  # Use the official Apache Airflow image version 2.4.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor  # Use LocalExecutor for Airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:letmeinplease@postgres/airflow  # Database connection string
      #AIRFLOW__CORE__FERNET_KEY: 'OExH4KfzQbFU9f2DltIorH3jDP6bHCjSIOXcjssHImM='  # Optional: Fernet key for encryption
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'  # Load example DAGs
    volumes:
      - ./dags:/opt/airflow/dags  # Mount local 'dags' directory to Airflow 'dags' directory
      - ./logs:/opt/airflow/logs  # Mount local 'logs' directory to Airflow 'logs' directory
      - ./plugins:/opt/airflow/plugins  # Mount local 'plugins' directory to Airflow 'plugins' directory
      - ./data:/opt/airflow/data # Mount local 'data' directory to Airflow 'data' directory
    depends_on:
      - postgres  # Ensure the PostgreSQL service is started before the scheduler
    command: scheduler  # Command to run the Airflow scheduler

  # Airflow initialization service
  airflow-init:
    build: .
    image: custom_airflow:latest  # Use the official Apache Airflow image version 2.4.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor  # Use LocalExecutor for Airflow
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:letmeinplease@postgres/airflow  # Database connection string
      #AIRFLOW__CORE__FERNET_KEY: 'OExH4KfzQbFU9f2DltIorH3jDP6bHCjSIOXcjssHImM='  # Optional: Fernet key for encryption
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'  # Load example DAGs
    volumes:
      - ./dags:/opt/airflow/dags  # Mount local 'dags' directory to Airflow 'dags' directory
      - ./logs:/opt/airflow/logs  # Mount local 'logs' directory to Airflow 'logs' directory
      - ./plugins:/opt/airflow/plugins  # Mount local 'plugins' directory to Airflow 'plugins' directory
      - ./data:/opt/airflow/data # Mount local 'data' directory to Airflow 'data' directory
    depends_on:
      - postgres  # Ensure the PostgreSQL service is started before the initialization
    entrypoint: >
      /bin/bash -c "sleep 10 && airflow db init && airflow users create --username admin1 --firstname Prashansa --lastname Dhakal --role Admin --email dhakalpa@mail.uc.edu --password letmeinplease"  # Initialize the Airflow database and create a new user

volumes:
  postgres-db-volume: {} # Define a named volume for PostgreSQL data
  pgadmin-data: {}
